# permissions for end users to view kubekillerservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubekillerserver-viewer-role
rules:
- apiGroups:
  - bullshitprogram.com
  resources:
  - kubekillerservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bullshitprogram.com
  resources:
  - kubekillerservers/status
  verbs:
  - get
