# permissions for end users to edit kubekillerservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubekillerserver-editor-role
rules:
- apiGroups:
  - bullshitprogram.com
  resources:
  - kubekillerservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bullshitprogram.com
  resources:
  - kubekillerservers/status
  verbs:
  - get
